language: python
sudo: required
dist: trusty
group: edge
python: 3.6
before_install:
  - sudo apt-get -qq update
install:
  - pip install tox
  - sudo apt-get update -y
  - sudo apt-get install build-essential curl file git
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda create -q -n test numpy pandas numexpr>=2.3.1 khmer>=2.0 sphinx>1.3.1 sphinx_rtd_theme>=0.1.9 nose>=1.3.4 nose-capturestderr>=1.0 doit>=0.3.0 matplotlib infernal blast crb-blast hmmer transdecoder last busco>=3.0.2 parallel
  - source activate test
  - pip install shmlast ficus --no-deps
  - pip install codecov
  - make install
script: make ci-test
