version: 0.2
env:
  variables:
      PATH: "$HOME/miniconda/bin:$HOME/.linuxbrew/bin:$PATH:$HOME/busco/scripts"

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install build-essential curl file git python-setuptools ruby liburi-escape-xs-perl emboss liburi-perl libsm6 libxrender1 libfontconfig1
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && bash miniconda.sh -b -p $HOME/miniconda
      - conda config --set always_yes yes --set changeps1 no
      - conda update -q conda
      - conda info -a
      - conda create -q -n test numpy scipy pandas matplotlib pytest pytest-cov coverage seaborn
      - source activate test
      - pip install shmlast --no-deps
      - pip install codecov
      - git clone https://github.com/Linuxbrew/brew.git $HOME/.linuxbrew
      - brew install homebrew/science/last homebrew/science/transdecoder parallel homebrew/science/blast homebrew/science/infernal homebrew/science/hmmer
      - pushd $HOME && git clone https://gitlab.com/ezlab/busco && cd busco && python setup.py install && popd
  build:
    commands:
      - make ci-test

